language: node_js
node_js:
  - "7"
sudo: required
group: stable
dist: trusty
os: linux
notifications:
  email:
    recipients:
      - timoweave@gmail.com
    on_success: always
    on_failure: always
